export default Object.freeze({
  NO_GAME: 'NO_GAME',

  START_GAME: 'START_GAME',
  LOADING: 'LOADING',
  WAITING_FOR_SERVER: 'WAITING_FOR_SERVER',
  DEAL_CARDS: 'DEAL_CARDS',
  GAME_OVER: 'GAME_OVER',

  PLAYER_TURN: 'PLAYER_TURN',
  PLAYER_TURN_PROCESSING: 'PLAYER_TURN_PROCESSING',

  COMPUTER_TURN: 'COMPUTER_TURN',
  COMPUTER_TURN_PROCESSING: 'COMPUTER_TURN_PROCESSING',

  ERROR: 'ERROR',
})
