export default Object.freeze({
  DRAW_TO_DISCARD: 'DRAW_TO_DISCARD',
  DRAW_TO_PLAYER: 'DRAW_TO_PLAYER',
  PLAYER_TO_DISCARD: 'PLAYER_TO_DISCARD',
  NOT_PLAY: 'NOT_PLAY',
  GAME_OVER: 'GAME_OVER',
})
